import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ChevronRight,Clock3,History,Home,Hourglass,RotateCcw,Settings,UserMinus,Users,Utensils,UserRoundCheck,X} from 'lucide-react';
import {byId,participants,themeColor} from './data';import {previewTurns} from './rotation';import {loadState,storage} from './storage';import type{AppState,HistoryEvent,ParticipantId,TabId}from'./types';
import {addPass,applyAbsenceSkip,changeNext as changeNextPayer,recordPayment as recordPaymentAction,resetState,saveManualPayment as saveManualPaymentAction,saveSplit as saveSplitAction,undoLast} from './appLogic';

const today=()=>new Date().toISOString().slice(0,10);
const dateLabel=(date?:string)=>date?new Intl.DateTimeFormat('es-DO',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`)):'';
const isThursday=(date:string)=>new Date(`${date}T12:00:00Z`).getUTCDay()===4;

function Avatar({id,size='md'}:{id:ParticipantId,size?:'sm'|'md'|'lg'}){const p=byId[id];return <img className={`avatar avatar-${size}`} src={p.photo} alt={p.name}/>}
function Modal({title,onClose,children}:{title:string,onClose:()=>void,children:React.ReactNode}){return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><button className="icon-btn close" onClick={onClose} aria-label="Cerrar"><X/></button><h2>{title}</h2>{children}</section></div>}
function DateField({value,onChange}:{value:string,onChange:(v:string)=>void}){return <label className="date-field"><span><CalendarDays size={18}/>Fecha de la Peña</span><input type="date" value={value} onChange={e=>onChange(e.target.value)} required/><small>{value&&isThursday(value)?'Jueves, como de costumbre ✨':'Usualmente nos juntamos los jueves, pero cualquier fecha funciona.'}</small></label>}

export default function App(){
 const[state,setState]=useState<AppState>(loadState);const[tab,setTab]=useState<TabId>('next');const[modal,setModal]=useState<'pay'|'skip'|'split'|'manual'|'undo'|'reset'|null>(null);const[recordDate,setRecordDate]=useState(today());const[splitIds,setSplitIds]=useState<ParticipantId[]>([]);const[splitAffects,setSplitAffects]=useState(false);const[manualPayer,setManualPayer]=useState<ParticipantId>('fidel');const[toast,setToast]=useState('');
 const current=byId[state.currentPayer];const upcoming=useMemo(()=>previewTurns(state.currentPayer,state.rotation,state.skips,4),[state]);
 useEffect(()=>storage.save(state),[state]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{document.querySelector('meta[name="theme-color"]')?.setAttribute('content',themeColor[state.currentPayer])},[state.currentPayer]);
 const commit=(next:AppState,message:string)=>{setState(next);setModal(null);setToast(message)};
 const recordPayment=()=>{const result=recordPaymentAction(state,recordDate);commit(result.state,result.message)};
 const confirmAbsenceSkip=()=>{const result=applyAbsenceSkip(state,recordDate);if(result)commit(result.state,result.message)};
 const addSkip=(id:ParticipantId,amount:number)=>setState(s=>addPass(s,id,amount));
 const changeNext=(id:ParticipantId)=>setState(s=>changeNextPayer(s,id));
 const saveSplit=()=>{if(!splitIds.length)return;commit(saveSplitAction(state,splitIds,splitAffects,recordDate),'Salida especial guardada.')};
 const saveManualPayment=()=>commit(saveManualPaymentAction(state,manualPayer,recordDate),`Pago manual de ${byId[manualPayer].name} guardado.`);
 const undo=()=>{const prev=undoLast(state);if(prev)commit(prev,'Última acción deshecha.')};
 const resetAll=()=>commit(resetState(state),'Datos originales restaurados.');
 const counts=Object.fromEntries(participants.map(p=>[p.id,state.history.filter(e=>(e.type==='payment'&&e.payer===p.id)||(e.type==='adjustment'&&e.action==='manual_payment'&&e.participant===p.id)).length])) as Record<ParticipantId,number>;

 return <main className={`app theme-${current.theme}`}><div className="ambient"/><div className="shell"><header><div className="brand-mark"><Utensils size={20}/></div><div><p className="eyebrow">La Peña de siempre</p><h1>PentaPeña</h1></div><div className="header-date"><Clock3 size={16}/><span>Jueves</span></div></header>
 <div className="content">
 {tab==='next'&&<section className="page"><p className="kicker">La próxima va por...</p><article className="hero"><img src={current.photo} alt={current.name}/><div className="hero-shade"/><div className="hero-copy"><span className="turn-pill">Te toca</span><h2>{current.name}</h2><p>Esta Peña lleva tu firma 🍽️</p></div></article><button className="primary" onClick={()=>{setRecordDate(today());setModal('pay')}}>Yo pagué 🍽️</button><button className="secondary wide" disabled={!!state.deferredPayer} onClick={()=>{setRecordDate(today());setModal('skip')}}><UserMinus size={18}/>Saltar esta Peña</button>{state.deferredPayer&&<p className="deferred-note"><Hourglass size={15}/>Después de esta Peña vuelve {byId[state.deferredPayer].name}.</p>}<section className="card upcoming"><div className="section-title"><div><p className="eyebrow">¿Quién sigue?</p><h3>Próximos</h3></div><ChevronRight/></div><div className="avatar-row">{upcoming.map((id,i)=><div className="mini-person" key={`${id}-${i}`}><Avatar id={id}/><span>{byId[id].name}</span>{i<upcoming.length-1&&<ChevronRight className="arrow" size={16}/>}</div>)}</div>{state.skips.fidel>0&&<p className="pass-note">Fidel tiene {state.skips.fidel} pase pendiente</p>}</section></section>}
 {tab==='history'&&<section className="page"><div className="page-heading"><p className="eyebrow">Los recuerdos</p><h2>Historial</h2><p>Sin cuentas. Solo quién puso la tarjeta sobre la mesa.</p></div><div className="history-list">{[...state.history].reverse().map((event,index)=><HistoryRow key={event.id} event={event} index={index}/>)}</div></section>}
 {tab==='group'&&<section className="page"><div className="page-heading"><p className="eyebrow">Los de siempre</p><h2>El grupo</h2><p>Cuatro amigos, una rotación y muchas sobremesas.</p></div><div className="stats"><div><strong>{state.history.filter(e=>e.type==='payment').length}</strong><span>Peñas registradas</span></div><div><strong>{state.history.filter(e=>e.type==='split').length}</strong><span>Salidas especiales</span></div></div><div className="people-grid">{participants.map((p,i)=><article className="person-card" key={p.id}><Avatar id={p.id} size="lg"/><div><h3>{p.name}</h3><p>{counts[p.id]} {counts[p.id]===1?'Peña':'Peñas'}</p></div><span className="position">#{state.rotation.indexOf(p.id)+1}</span>{state.skips[p.id]>0&&<span className="badge">{state.skips[p.id]} pase</span>}{state.currentPayer===p.id&&<span className="next-badge">Sigue</span>}</article>)}</div></section>}
 {tab==='settings'&&<section className="page"><div className="page-heading"><p className="eyebrow">Cuando la vida pasa</p><h2>Ajustes</h2><p>Cambia el turno, reparte pases o registra una salida distinta.</p></div><section className="card settings-card"><h3>Pases</h3>{participants.map(p=><div className="setting-row" key={p.id}><div className="person-inline"><Avatar id={p.id} size="sm"/><span>{p.name}</span></div><div className="stepper"><button onClick={()=>addSkip(p.id,-1)} disabled={!state.skips[p.id]} aria-label={`Quitar pase a ${p.name}`}>−</button><strong>{state.skips[p.id]}</strong><button onClick={()=>addSkip(p.id,1)} aria-label={`Dar pase a ${p.name}`}>+</button></div></div>)}</section><section className="card settings-card"><h3>Cambiar quién sigue</h3><div className="choice-row">{participants.map(p=><button className={state.currentPayer===p.id?'selected':''} onClick={()=>changeNext(p.id)} key={p.id}><Avatar id={p.id} size="sm"/><span>{p.name}</span></button>)}</div></section><button className="secondary wide" onClick={()=>{setRecordDate(today());setSplitIds([]);setModal('split')}}><Users/>Salida especial</button><button className="secondary wide" onClick={()=>{setRecordDate(today());setManualPayer(state.currentPayer);setModal('manual')}}><CalendarDays/>Agregar pago manual</button><button className="secondary wide" disabled={!state.undo} onClick={()=>setModal('undo')}><RotateCcw/>Deshacer última acción</button><button className="danger-link" onClick={()=>setModal('reset')}>Restablecer datos originales</button></section>}
 </div><nav>{([{id:'next',label:'Próxima',icon:Home},{id:'history',label:'Historial',icon:History},{id:'group',label:'Grupo',icon:Users},{id:'settings',label:'Ajustes',icon:Settings}] as const).map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}><item.icon/><span>{item.label}</span></button>)}</nav></div>
 {modal==='pay'&&<Modal title={`¿Registrar que ${current.name} pagó?`} onClose={()=>setModal(null)}><div className="modal-person"><Avatar id={current.id} size="lg"/><p>La Peña quedará en el historial y el turno avanzará automáticamente.</p></div><DateField value={recordDate} onChange={setRecordDate}/><div className="modal-actions"><button className="primary" onClick={recordPayment} disabled={!recordDate}>Sí, {current.name} pagó</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {modal==='skip'&&<Modal title={`¿${current.name} no puede asistir?`} onClose={()=>setModal(null)}><div className="modal-person"><Avatar id={current.id} size="lg"/><p>Se elegirá a otro participante para cubrir esta Peña. {current.name} queda pendiente y será el próximo en cuanto el sustituto pague.</p></div><DateField value={recordDate} onChange={setRecordDate}/><div className="modal-actions"><button className="primary" onClick={confirmAbsenceSkip} disabled={!recordDate}>Saltar esta Peña</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {modal==='split'&&<Modal title="Salida especial" onClose={()=>setModal(null)}><p className="modal-intro">¿Quiénes participaron en el pago?</p><div className="check-grid">{participants.map(p=><label key={p.id} className={splitIds.includes(p.id)?'checked':''}><input type="checkbox" checked={splitIds.includes(p.id)} onChange={()=>setSplitIds(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}/><Avatar id={p.id} size="sm"/><span>{p.name}</span></label>)}</div><DateField value={recordDate} onChange={setRecordDate}/><label className="toggle-row"><input type="checkbox" checked={splitAffects} onChange={e=>setSplitAffects(e.target.checked)}/><span><strong>Actualizar la rotación</strong><small>Si no, solo se guarda en el historial.</small></span></label><div className="modal-actions"><button className="primary" onClick={saveSplit} disabled={!splitIds.length||!recordDate}>Guardar salida</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {modal==='manual'&&<Modal title="Agregar pago manual" onClose={()=>setModal(null)}><p className="modal-intro">Para corregir el historial sin mover el turno actual.</p><div className="choice-row">{participants.map(p=><button className={manualPayer===p.id?'selected':''} onClick={()=>setManualPayer(p.id)} key={p.id}><Avatar id={p.id} size="sm"/><span>{p.name}</span></button>)}</div><DateField value={recordDate} onChange={setRecordDate}/><div className="modal-actions"><button className="primary" onClick={saveManualPayment} disabled={!recordDate}>Guardar pago manual</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {modal==='undo'&&<Modal title="¿Deshacer la última acción?" onClose={()=>setModal(null)}><p className="modal-intro">Se restaurará el turno, los pases y el historial anterior.</p><div className="modal-actions"><button className="primary" onClick={undo}>Sí, deshacer</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {modal==='reset'&&<Modal title="¿Volver al inicio?" onClose={()=>setModal(null)}><p className="modal-intro">Manu volverá a ser el próximo y Fidel recuperará su pase original.</p><div className="modal-actions"><button className="danger" onClick={resetAll}>Restablecer</button><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button></div></Modal>}
 {toast&&<div className="toast" role="status"><UserRoundCheck/>{toast}</div>}</main>
}

function HistoryRow({event,index}:{event:HistoryEvent,index:number}){
 if(event.type==='payment'){const p=byId[event.payer];return <article className="history-row"><Avatar id={p.id}/><div><h3>{p.name}</h3><p>{event.date?dateLabel(event.date):event.label??(index===0?'Última Peña':'Peña anterior')}</p></div><Utensils/></article>}
 if(event.type==='split')return <article className="history-row split"><div className="event-icon"><Users/></div><div><h3>Salida especial</h3><p>{dateLabel(event.createdAt.slice(0,10))} · {event.participants.map(id=>byId[id].name).join(', ')}</p></div></article>;
 if(event.action==='absence_skip'){const p=event.participant?byId[event.participant]:null;return <article className="history-row absence"><div className="event-icon"><Hourglass/></div><div><h3>{p?.name} no pudo asistir</h3><p>{event.date?dateLabel(event.date):''} · {event.nextPayer?`Cubrió ${byId[event.nextPayer].name}`:''}</p></div></article>}
 if(event.action==='manual_payment'){const p=event.participant?byId[event.participant]:null;return <article className="history-row"><Avatar id={event.participant!}/><div><h3>{p?.name}</h3><p>{event.date?dateLabel(event.date):''} · Pago manual</p></div><Utensils/></article>}
 const p=event.participant?byId[event.participant]:null;return <article className="history-row adjustment"><div className="event-icon"><Settings/></div><div><h3>Ajuste manual</h3><p>{p?.name??'Rotación'} · {event.action.replace('_',' ')}</p></div></article>
}
